import { FeedItem } from '../types/coverage';

/**
 * SEED REGISTRY - Todos os Transportes de Portugal
 * Conforme especificações oficiais e diretrizes nacionais.
 * Cada operador possui o URL primário e o espelho urls.latest do Mobility Database.
 */
export const SEED_FEEDS: FeedItem[] = [
  // --- Lisboa e Setúbal ---
  {
    id: 'carris_metropolitana',
    operator_name: 'Carris Metropolitana',
    mode: 'Autocarro',
    feed_type: 'api',
    source_origin: 'seed',
    url: '', // Não incluído no arranque: ficheiro demasiado grande (Regra 4)
    latest_url: '',
    license_url: 'https://dados.gov.pt/pt/datasets/gtfs-carris-metropolitana/',
    auth_type: 'none',
    status: 'SEM DADOS',
    progress: 'Não incluído no arranque (ficheiro demasiado grande)',
    lines_count: 0,
    stops_count: 0,
    trips_count: 0,
    realtime_entities: 'https://api.carrismetropolitana.pt/v2',
  },
  {
    id: 'carris',
    operator_name: 'Carris (Lisboa)',
    mode: 'Autocarro / Elétrico',
    feed_type: 'gtfs',
    source_origin: 'seed',
    url: '',
    latest_url: '',
    license_url: 'https://www.carris.pt/dados-abertos/',
    auth_type: 'none',
    status: 'SEM DADOS',
    lines_count: 0,
    stops_count: 0,
    trips_count: 0,
    realtime_entities: 'não integrado',
  },
  {
    id: 'metro_lisboa',
    operator_name: 'Metro de Lisboa',
    mode: 'Metro',
    feed_type: 'gtfs',
    source_origin: 'seed',
    url: 'https://www.metrolisboa.pt/google_transit/googleTransit.zip',
    latest_url: 'https://www.metrolisboa.pt/google_transit/googleTransit.zip',
    license_url: 'https://www.metrolisboa.pt/transparencia/dados-abertos/',
    auth_type: 'none',
    status: 'A aguardar',
    lines_count: 0,
    stops_count: 0,
    trips_count: 0,
    realtime_entities: 'https://api.metrolisboa.pt',
  },
  {
    id: 'cp',
    operator_name: 'CP – Comboios de Portugal',
    mode: 'Comboio',
    feed_type: 'gtfs',
    source_origin: 'seed',
    url: 'https://publico.cp.pt/gtfs/gtfs.zip',
    latest_url: 'https://publico.cp.pt/gtfs/gtfs.zip',
    license_url: 'https://www.cp.pt/passageiros/pt/informacao-geral/termos-condicoes',
    auth_type: 'none',
    status: 'A aguardar',
    lines_count: 0,
    stops_count: 0,
    trips_count: 0,
    realtime_entities: 'não integrado',
  },
  {
    id: 'fertagus',
    operator_name: 'Fertagus',
    mode: 'Comboio',
    feed_type: 'gtfs',
    source_origin: 'seed',
    url: 'https://www.fertagus.pt/GTFSTMLzip/Fertagus_GTFS.zip',
    latest_url: 'https://www.fertagus.pt/GTFSTMLzip/Fertagus_GTFS.zip',
    license_url: 'https://www.fertagus.pt/',
    auth_type: 'none',
    status: 'A aguardar',
    lines_count: 0,
    stops_count: 0,
    trips_count: 0,
    realtime_entities: 'não integrado',
  },
  {
    id: 'transtejo_soflusa',
    operator_name: 'Transtejo Soflusa',
    mode: 'Barco',
    feed_type: 'gtfs',
    source_origin: 'seed',
    url: 'https://files.mobilitydatabase.org/mdb-2921/latest.zip',
    latest_url: 'https://files.mobilitydatabase.org/mdb-2921/latest.zip',
    license_url: 'https://ttsl.pt/termos-e-condicoes/',
    auth_type: 'none',
    status: 'A aguardar',
    lines_count: 0,
    stops_count: 0,
    trips_count: 0,
    realtime_entities: 'não integrado',
  },
  {
    id: 'mts',
    operator_name: 'Metro Sul do Tejo',
    mode: 'Metro Ligeiro / Elétrico',
    feed_type: 'gtfs',
    source_origin: 'seed',
    url: 'https://mts.pt/imt/MTS-20240129.zip',
    latest_url: 'https://mts.pt/imt/MTS-20240129.zip',
    license_url: 'https://mts.pt/',
    auth_type: 'none',
    status: 'A aguardar',
    lines_count: 0,
    stops_count: 0,
    trips_count: 0,
    realtime_entities: 'não integrado',
  },
  {
    id: 'tcb_barreiro',
    operator_name: 'TCB Barreiro',
    mode: 'Autocarro',
    feed_type: 'gtfs',
    source_origin: 'seed',
    url: 'https://backend.tcbarreiro.pt/download-gtfs',
    latest_url: 'https://backend.tcbarreiro.pt/download-gtfs',
    license_url: 'https://www.tcbarreiro.pt/',
    auth_type: 'none',
    status: 'A aguardar',
    lines_count: 0,
    stops_count: 0,
    trips_count: 0,
    realtime_entities: 'não integrado',
  },

  // --- Porto ---
  {
    id: 'stcp',
    operator_name: 'STCP',
    mode: 'Autocarro / Elétrico',
    feed_type: 'gtfs',
    source_origin: 'seed',
    url: 'https://dadosabertos.cm-porto.pt/dataset/71490e40-9e19-11f1-84ed-6abdb6d5cf34/resource/51340c18-0ef5-4895-b099-cf7247ea54f4/download/gtfs_feed.zip',
    latest_url: 'https://dadosabertos.cm-porto.pt/dataset/71490e40-9e19-11f1-84ed-6abdb6d5cf34/resource/51340c18-0ef5-4895-b099-cf7247ea54f4/download/gtfs_feed.zip',
    license_url: 'https://opendata.porto.digital/dataset/horarios-paragens-e-rotas-em-formato-gtfs-stcp',
    auth_type: 'none',
    status: 'horário expirado',
    progress: 'horário desatualizado',
    valid_from: '2026-09-01',
    valid_until: '2026-09-23',
    lines_count: 0,
    stops_count: 0,
    trips_count: 0,
    realtime_entities: 'https://dadosabertos.cm-porto.pt/api/3/action/datastore_search',
  },
  {
    id: 'metro_porto',
    operator_name: 'Metro do Porto',
    mode: 'Metro',
    feed_type: 'gtfs',
    source_origin: 'seed',
    url: 'https://files.mobilitydatabase.org/mdb-2357/latest.zip',
    latest_url: 'https://files.mobilitydatabase.org/mdb-2357/latest.zip',
    license_url: 'https://opendata.porto.digital/dataset/horarios-paragens-e-rotas-em-formato-gtfs',
    auth_type: 'none',
    status: 'A aguardar',
    lines_count: 0,
    stops_count: 0,
    trips_count: 0,
    realtime_entities: 'não integrado',
  },
  {
    id: 'unir',
    operator_name: 'UNIR (Área Metropolitana do Porto)',
    mode: 'Autocarro',
    feed_type: 'api',
    source_origin: 'AMP QiHoras (não oficial)',
    url: 'https://files.mobilitydatabase.org/mdb-2550/latest.zip',
    latest_url: 'https://files.mobilitydatabase.org/mdb-2550/latest.zip',
    license_url: 'https://paragens.amp.pt/',
    auth_type: 'none',
    status: 'A aguardar',
    lines_count: 0,
    stops_count: 0,
    trips_count: 0,
    realtime_entities: 'https://paragens.amp.pt/geoserver/paragens/ows',
  },

  // --- Norte ---
  {
    id: 'tub_braga',
    operator_name: 'TUB Braga',
    mode: 'Autocarro',
    feed_type: 'gtfs',
    source_origin: 'seed',
    url: 'https://www.tub.pt/developer/gtfs/feed/tub.zip',
    latest_url: 'https://www.tub.pt/developer/gtfs/feed/tub.zip',
    license_url: 'https://www.tub.pt/',
    auth_type: 'none',
    status: 'A aguardar',
    lines_count: 0,
    stops_count: 0,
    trips_count: 0,
    realtime_entities: 'não integrado',
  },
  {
    id: 'guimabus',
    operator_name: 'Guimabus Guimarães',
    mode: 'Autocarro',
    feed_type: 'gtfs',
    source_origin: 'seed',
    url: 'https://map.mobility.ubiwhere.com/dataset/ee6d46e4-9f19-4f4a-ab93-1a3cd69df349/resource/08f1ee6c-2d3f-4fb3-a861-5d6fb347a6d4/download/gtfs_gui.zip',
    latest_url: 'https://map.mobility.ubiwhere.com/dataset/ee6d46e4-9f19-4f4a-ab93-1a3cd69df349/resource/08f1ee6c-2d3f-4fb3-a861-5d6fb347a6d4/download/gtfs_gui.zip',
    license_url: 'https://map.mobility.ubiwhere.com/',
    auth_type: 'none',
    status: 'A aguardar',
    lines_count: 0,
    stops_count: 0,
    trips_count: 0,
    realtime_entities: 'não integrado',
  },
  {
    id: 'tuba_barcelos',
    operator_name: 'TUBA Barcelos',
    mode: 'Autocarro',
    feed_type: 'gtfs',
    source_origin: 'seed',
    url: 'https://map.mobility.ubiwhere.com/dataset/1842a15c-1aec-4f65-8e29-e57c8b4cbd74/resource/a595ee4b-bf86-4323-b1f4-7e3b3eb00e5e/download/gtfs_bar.zip',
    latest_url: 'https://map.mobility.ubiwhere.com/dataset/1842a15c-1aec-4f65-8e29-e57c8b4cbd74/resource/a595ee4b-bf86-4323-b1f4-7e3b3eb00e5e/download/gtfs_bar.zip',
    license_url: 'https://map.mobility.ubiwhere.com/',
    auth_type: 'none',
    status: 'A aguardar',
    lines_count: 0,
    stops_count: 0,
    trips_count: 0,
    realtime_entities: 'não integrado',
  },
  {
    id: 'mobiave_famalicao',
    operator_name: 'Mobiave Famalicão',
    mode: 'Autocarro',
    feed_type: 'gtfs',
    source_origin: 'seed',
    url: 'https://map.mobility.ubiwhere.com/dataset/fe6015e4-86c7-437a-8d31-10759fe21a1d/resource/7ac67ef8-015c-42e8-9546-f6f0be956270/download/gtfs_vnf.zip',
    latest_url: 'https://map.mobility.ubiwhere.com/dataset/fe6015e4-86c7-437a-8d31-10759fe21a1d/resource/7ac67ef8-015c-42e8-9546-f6f0be956270/download/gtfs_vnf.zip',
    license_url: 'https://map.mobility.ubiwhere.com/',
    auth_type: 'none',
    status: 'A aguardar',
    lines_count: 0,
    stops_count: 0,
    trips_count: 0,
    realtime_entities: 'não integrado',
  },

  // --- Centro ---
  {
    id: 'smtuc_coimbra',
    operator_name: 'SMTUC Coimbra',
    mode: 'Autocarro / Trólecar',
    feed_type: 'gtfs',
    source_origin: 'seed',
    url: 'https://files.mobilitydatabase.org/mdb-2992/latest.zip',
    latest_url: 'https://files.mobilitydatabase.org/mdb-2992/latest.zip',
    license_url: 'https://dados.gov.pt/pt/datasets/gtfs-estaticos-servicos-municipalizados-de-transportes-urbanos-de-coimbra/',
    auth_type: 'none',
    status: 'A aguardar',
    lines_count: 0,
    stops_count: 0,
    trips_count: 0,
    realtime_entities: 'não integrado',
  },

  // --- Algarve ---
  {
    id: 'vamus_algarve',
    operator_name: 'Vamus Algarve',
    mode: 'Autocarro',
    feed_type: 'gtfs',
    source_origin: 'seed',
    url: 'https://files.mobilitydatabase.org/tld-4315/latest.zip',
    latest_url: 'https://files.mobilitydatabase.org/tld-4315/latest.zip',
    license_url: 'https://vamusalgarve.pt/',
    auth_type: 'none',
    status: 'A aguardar',
    lines_count: 0,
    stops_count: 0,
    trips_count: 0,
    realtime_entities: 'não integrado',
  },
  {
    id: 'proximo_faro',
    operator_name: 'Próximo Faro',
    mode: 'Autocarro',
    feed_type: 'gtfs',
    source_origin: 'seed',
    url: 'https://files.mobilitydatabase.org/tld-4321/latest.zip',
    latest_url: 'https://files.mobilitydatabase.org/tld-4321/latest.zip',
    license_url: 'https://proximo.pt/',
    auth_type: 'none',
    status: 'A aguardar',
    lines_count: 0,
    stops_count: 0,
    trips_count: 0,
    realtime_entities: 'não integrado',
  },
  {
    id: 'giro_albufeira',
    operator_name: 'GIRO Albufeira',
    mode: 'Autocarro',
    feed_type: 'gtfs',
    source_origin: 'seed',
    url: 'https://files.mobilitydatabase.org/tld-4320/latest.zip',
    latest_url: 'https://files.mobilitydatabase.org/tld-4320/latest.zip',
    license_url: 'https://www.cm-albufeira.pt/',
    auth_type: 'none',
    status: 'A aguardar',
    lines_count: 0,
    stops_count: 0,
    trips_count: 0,
    realtime_entities: 'não integrado',
  },
  {
    id: 'sobe_e_desce_tavira',
    operator_name: 'Sobe e Desce Tavira',
    mode: 'Autocarro',
    feed_type: 'gtfs',
    source_origin: 'seed',
    url: 'https://files.mobilitydatabase.org/tld-4322/latest.zip',
    latest_url: 'https://files.mobilitydatabase.org/tld-4322/latest.zip',
    license_url: 'https://cm-tavira.pt/',
    auth_type: 'none',
    status: 'A aguardar',
    lines_count: 0,
    stops_count: 0,
    trips_count: 0,
    realtime_entities: 'não integrado',
  },

  // --- Madeira ---
  {
    id: 'horarios_funchal',
    operator_name: 'Horários do Funchal',
    mode: 'Autocarro',
    feed_type: 'gtfs',
    source_origin: 'seed',
    url: 'https://www.horariosdofunchal.pt/googletransit.zip',
    latest_url: 'https://files.mobilitydatabase.org/mdb-3104/latest.zip',
    license_url: 'https://www.horariosdofunchal.pt/',
    auth_type: 'none',
    status: 'A aguardar',
    lines_count: 0,
    stops_count: 0,
    trips_count: 0,
    realtime_entities: 'não integrado',
  },

  // --- Outros Operadores do Catálogo Nacional (Sem URL direto GTFS disponível) ---
  {
    id: 'mobicascais',
    operator_name: 'MobiCascais (Cascais Próxima)',
    mode: 'Autocarro',
    feed_type: 'api',
    source_origin: 'catálogo',
    url: '',
    latest_url: '',
    license_url: 'https://www.mobicascais.pt/',
    auth_type: 'none',
    status: 'SEM DADOS',
    progress: 'Sem feed GTFS público direto',
    lines_count: 0,
    stops_count: 0,
    trips_count: 0,
    realtime_entities: 'não integrado',
  },
  {
    id: 'mobilis_leiria',
    operator_name: 'Mobilis (Leiria)',
    mode: 'Autocarro',
    feed_type: 'api',
    source_origin: 'catálogo',
    url: '',
    latest_url: '',
    license_url: 'https://mobilis.pt/',
    auth_type: 'none',
    status: 'SEM DADOS',
    progress: 'Sem feed GTFS público direto',
    lines_count: 0,
    stops_count: 0,
    trips_count: 0,
    realtime_entities: 'não integrado',
  },
  {
    id: 'muv_viana',
    operator_name: 'MUV - Mobilidade de Viana do Castelo',
    mode: 'Autocarro',
    feed_type: 'api',
    source_origin: 'catálogo',
    url: '',
    latest_url: '',
    license_url: 'https://muv.cm-viana-castelo.pt/',
    auth_type: 'none',
    status: 'SEM DADOS',
    progress: 'Sem feed GTFS público direto',
    lines_count: 0,
    stops_count: 0,
    trips_count: 0,
    realtime_entities: 'não integrado',
  },
  {
    id: 'tut_torres_vedras',
    operator_name: 'TUT - Transportes Urbanos de Torres Vedras',
    mode: 'Autocarro',
    feed_type: 'api',
    source_origin: 'catálogo',
    url: '',
    latest_url: '',
    license_url: 'https://www.cm-tvedras.pt/',
    auth_type: 'none',
    status: 'SEM DADOS',
    progress: 'Sem feed GTFS público direto',
    lines_count: 0,
    stops_count: 0,
    trips_count: 0,
    realtime_entities: 'não integrado',
  },
  {
    id: 'covilha_mobilidade',
    operator_name: 'Covilhã Mobilidade (Movicovilhã)',
    mode: 'Autocarro',
    feed_type: 'api',
    source_origin: 'catálogo',
    url: '',
    latest_url: '',
    license_url: 'https://movicovilha.pt/',
    auth_type: 'none',
    status: 'SEM DADOS',
    progress: 'Sem feed GTFS público direto',
    lines_count: 0,
    stops_count: 0,
    trips_count: 0,
    realtime_entities: 'não integrado',
  },
  {
    id: 'aveirobus',
    operator_name: 'AveiroBus (Mobilidade de Aveiro)',
    mode: 'Autocarro / Barco',
    feed_type: 'api',
    source_origin: 'catálogo',
    url: '',
    latest_url: '',
    license_url: 'https://aveirobus.pt/',
    auth_type: 'none',
    status: 'SEM DADOS',
    progress: 'Sem feed GTFS público direto',
    lines_count: 0,
    stops_count: 0,
    trips_count: 0,
    realtime_entities: 'não integrado',
  },
  {
    id: 'tce_evora',
    operator_name: 'Transportes Coletivos de Évora (Trevo)',
    mode: 'Autocarro',
    feed_type: 'api',
    source_origin: 'catálogo',
    url: '',
    latest_url: '',
    license_url: 'https://trevo.com.pt/',
    auth_type: 'none',
    status: 'SEM DADOS',
    progress: 'Sem feed GTFS público direto',
    lines_count: 0,
    stops_count: 0,
    trips_count: 0,
    realtime_entities: 'não integrado',
  },

  // --- Longa Distância (carregar por último) ---
  {
    id: 'flixbus_pt',
    operator_name: 'FlixBus Portugal',
    mode: 'Autocarro Longo Curso',
    feed_type: 'gtfs',
    source_origin: 'seed',
    url: 'https://gtfs.gis.flix.tech/gtfs_generic_eu.zip',
    latest_url: 'https://gtfs.gis.flix.tech/gtfs_generic_eu.zip',
    license_url: 'https://transport.data.gouv.fr/resources/11681',
    auth_type: 'none',
    status: 'A aguardar',
    lines_count: 0,
    stops_count: 0,
    trips_count: 0,
    realtime_entities: 'não integrado',
  },
];

/**
 * Expected Networks Checklist definitions
 */
export const EXPECTED_NETWORKS = [
  { name: 'Carris Metropolitana', mode: 'Autocarro', defaultSeedId: 'carris_metropolitana' },
  { name: 'Carris', mode: 'Autocarro / Elétrico', defaultSeedId: 'carris' },
  { name: 'Metro de Lisboa', mode: 'Metro', defaultSeedId: 'metro_lisboa' },
  { name: 'CP', mode: 'Comboio', defaultSeedId: 'cp' },
  { name: 'Fertagus', mode: 'Comboio', defaultSeedId: 'fertagus' },
  { name: 'Transtejo/Soflusa', mode: 'Barco', defaultSeedId: 'transtejo_soflusa' },
  { name: 'Metro Transportes do Sul', mode: 'Metro Ligeiro / Elétrico', defaultSeedId: 'mts' },
  { name: 'TCB Barreiro', mode: 'Autocarro', defaultSeedId: 'tcb_barreiro' },
  { name: 'STCP', mode: 'Autocarro / Elétrico', defaultSeedId: 'stcp' },
  { name: 'Metro do Porto', mode: 'Metro', defaultSeedId: 'metro_porto' },
  { name: 'UNIR', mode: 'Autocarro', defaultSeedId: 'unir' },
  { name: 'TUB (Braga)', mode: 'Autocarro', defaultSeedId: 'tub_braga' },
  { name: 'Guimabus (Guimarães)', mode: 'Autocarro', defaultSeedId: 'guimabus' },
  { name: 'TUBA (Barcelos)', mode: 'Autocarro', defaultSeedId: 'tuba_barcelos' },
  { name: 'Mobiave (Famalicão)', mode: 'Autocarro', defaultSeedId: 'mobiave_famalicao' },
  { name: 'SMTUC (Coimbra)', mode: 'Autocarro / Trólecar', defaultSeedId: 'smtuc_coimbra' },
  { name: 'Vamus Algarve', mode: 'Autocarro', defaultSeedId: 'vamus_algarve' },
  { name: 'Próximo (Faro)', mode: 'Autocarro', defaultSeedId: 'proximo_faro' },
  { name: 'GIRO (Albufeira)', mode: 'Autocarro', defaultSeedId: 'giro_albufeira' },
  { name: 'Sobe e Desce (Tavira)', mode: 'Autocarro', defaultSeedId: 'sobe_e_desce_tavira' },
  { name: 'Horários do Funchal', mode: 'Autocarro', defaultSeedId: 'horarios_funchal' },
  { name: 'FlixBus (Portugal)', mode: 'Autocarro Longo Curso', defaultSeedId: 'flixbus_pt' },
];
